### PR TITLE
Adding support for firewall as input parameter for create server

### PR DESCRIPTION
**Pull request by easyStartup-pulse**
https://docs.hetzner.cloud/#servers-create-a-server

### CODE REVIEW

**Comment by tomsiewert** [comment]
I don't question why the v1 api design is so inconsistent and fucked up when Networking features are involved...

Anyway, thanks for your PR! The failing tests are okay since you don't have a token defined in your fork. I'll release it after some fixes on my side (some API fields were silently dropped).

**Review by tomsiewert — APPROVED** [review]

**Comment by easyStartup-pulse** [comment]
also @tomsiewert  there is some issue with your release because maven does not yet have the 3.2 version https://mvnrepository.com/artifact/me.tomsdevsn/hetznercloud-api . For my purpose i have created a jar locally to embedd in my application , but please look into it

**Comment by tomsiewert** [comment]
Ayy, the mvn action failed. Unfortunately, the logs already expired. I'll check if I can push it to maven central again.

**Comment by tomsiewert** [comment]
@easyStartup-pulse maven-source-plugin 3.3.0 broke the release. v3.2.1 is now online.

**Pull request merged**
